// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgvkifrSGLmjpTI0_hpVmtHawJGhtqzc',
    appId: '1:436363627484:web:9d3190a33e7e9847029d19',
    messagingSenderId: '436363627484',
    projectId: 'benchmark-14acf',
    authDomain: 'benchmark-14acf.firebaseapp.com',
    storageBucket: 'benchmark-14acf.firebasestorage.app',
    measurementId: 'G-BG8B2BXN9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYJISpxKZLrWT09MQEt5gZNPb2EpCXWE',
    appId: '1:436363627484:android:08498a89d5e2cead029d19',
    messagingSenderId: '436363627484',
    projectId: 'benchmark-14acf',
    storageBucket: 'benchmark-14acf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQJHX4m5NEKFSHMkPeEnU5IP7N0IR6Rw',
    appId: '1:436363627484:ios:a4b1b3e38dbbc23e029d19',
    messagingSenderId: '436363627484',
    projectId: 'benchmark-14acf',
    storageBucket: 'benchmark-14acf.firebasestorage.app',
    iosBundleId: 'com.example.benchmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQJHX4m5NEKFSHMkPeEnU5IP7N0IR6Rw',
    appId: '1:436363627484:ios:a4b1b3e38dbbc23e029d19',
    messagingSenderId: '436363627484',
    projectId: 'benchmark-14acf',
    storageBucket: 'benchmark-14acf.firebasestorage.app',
    iosBundleId: 'com.example.benchmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdgvkifrSGLmjpTI0_hpVmtHawJGhtqzc',
    appId: '1:436363627484:web:6a27e6976fd3c0f2029d19',
    messagingSenderId: '436363627484',
    projectId: 'benchmark-14acf',
    authDomain: 'benchmark-14acf.firebaseapp.com',
    storageBucket: 'benchmark-14acf.firebasestorage.app',
    measurementId: 'G-BYCW5NG2FE',
  );
}
